# 2022-10-29
# Hyperling.com configuration.

services:
  app:
    container_name: www-app
    build:
      context: ./
      network: host
    restart: always
    ports:
      - 8317:8080
    volumes:
      - ./files:/var/www/api/files
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
