# 2022-10-05 Hyperling
# Reverse Proxy
# This is a revised version of the original work here:
#   https://phoenixnap.com/kb/docker-nginx-reverse-proxy
#   https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/

version: '2'

services:
  app:
    image: nginx
    restart: always
    build: ./
    ports:
      - 80:80
      - 443:443
