# Nextcloud configuration.
# This is a revised version of the original work here:
#   https://hub.docker.com/_/nextcloud

# Changelog:
# 2023-07-16 Change from mariadb:10.5 to 10.6.
# 2023-08-20 Add Redis. (https://markontech.com/docker/setup-nextcloud-with-redis-using-docker/)

version: '2'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ../../Volumes/Nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ChangeMe
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nc
      - MYSQL_PASSWORD=changeme

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass someredispassword

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
      - redis
    volumes:
      - ../../Volumes/Nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nc
      - MYSQL_PASSWORD=changeme
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=5G
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=someredispassword
