# Nextcloud configuration.
# This is a revised version of the original work here: 
#   https://hub.docker.com/_/nextcloud

version: '2'

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/Docker/Volumes/Nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ChangeMe
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nc
      - MYSQL_PASSWORD=changeme

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /opt/Docker/Volumes/Nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nc
      - MYSQL_PASSWORD=changeme
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=5G

