# Nextcloud configuration.
# This is a revised version of the original work here:
#   https://hub.docker.com/_/nextcloud

# Changelog:
# 2023-07-16 Change from mariadb:10.5 to 10.6.
# 2023-08-20 Add Redis. (https://markontech.com/docker/setup-nextcloud-with-redis-using-docker/)

version: '3'

services:
  db:
    container_name: nc-db
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ../../Volumes/Nextcloud/mariadb:/var/lib/mysql

  redis:
    container_name: nc-redis
    image: redis
    restart: always
    command: redis-server --requirepass $REDIS_HOST_PASSWORD

  app:
    container_name: nc-app
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
      - redis
    volumes:
      - ../../Volumes/Nextcloud/nextcloud:/var/www/html
    dns:
      - "$DNS"
