# 2024-12-30 Hyperling
# Gogs self-hosted git server!
#   https://hub.docker.com/r/gogs/gogs
#   https://gist.github.com/ahromis/4ce4a58623847ca82cb1b745c2f83c82

## TBD UNTESTED ##

services:

  app:
    ## Database ##
    # SQL Lite

    ## App ##
    container_name: gogs-app
    image: gogs/gogs:latest
    restart: always
    ports:
      - "8002:80"
      - "3002:3000"
      - "2202:22"
    volumes:
      - ../../Volumes/Gogs/gogs:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "RUN_CROND=true"
    #networks:
    #  - gogs
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
