# 2024-12-30 Hyperling
# Gitea self-hosted git server!
#   https://hub.docker.com/r/gitea/gitea
#   https://docs.gitea.com/installation/install-with-docker

# Takes nearly double the resources of Gogs.
# Has a nicer UI and more features. Can anyone say, "Dark Theme"? ;D

services:

  app:
    ## Database ##
    # SQL Lite

    ## App ##
    container_name: gitea-app
    image: gitea/gitea:latest
    restart: always
    ports:
      - "3001:3000"
      - "2201:22"
    volumes:
      - ../../Volumes/Gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    #networks:
    #  - gitea
    deploy:
      mode: global
      resources:
        limits:
        # Minimum requirements for processes to start properly.
        # Takes a while to start up and migrate projects, but does work.
          ###cpus: '0.05'
          ###memory: 64M
        # Production-quality performance.
          ###cpus: '0.10'
          ###memory: 128M
        # Extra! Idles around 120M but exceeds 170M sometimes after busy.
          ###cpus: '0.25'
          ###memory: 192M
        # Final thoughts after tests.
          cpus: '0.50'
          memory: 192M

## Test Results ##
# 0.05 CPU, 64MB RAM
# - Migrate https://github.com/hyperling/ansible
#   - Page: 10512ms Template: 2111ms
# - Migrate https://github.com/hyperling/website
#   - Page: 6514ms  Template: 807ms
# - Migrate https://github.com/hyperling/docker
#   - Page: 8105ms  Template: 1201ms
# 0.10 CPU, 128MB RAM
# - Migrate https://github.com/hyperling/ansible
#   - Page: 2501ms Template: 294ms
# - Migrate https://github.com/hyperling/website
#   - Page: 786ms Template: 194ms
# - Migrate https://github.com/hyperling/docker
#   - Page: 1283ms Template: 87ms
# 0.25 CPU, 192MB RAM
# - Migrate https://github.com/hyperling/ansible
#   - Page: 439ms Template: 101ms
# - Migrate https://github.com/hyperling/website
#   - Page: 541ms Template: 2ms
# - Migrate https://github.com/hyperling/docker
#   - Page: 254ms Template: 86ms
## ##
